site_name: MatConvNet
markdown_extensions: ['extra', 'mathjax']
theme: bootstrap

extra_css: ['css/tables.css', 'css/fixes.css']
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML', 'js/mathjaxhelper.js']

repo_url: https://github.com/vlfeat/matconvnet

pages:
- ['index.md', 'MatConvNet: CNNs for MATLAB']

- ['install.md', 'Getting Started', 'Installing']
- ['pretrained.md', 'Getting Started', 'Pretrained models']
- ['training.md', 'Getting Started', 'Training new models']
- ['gpu.md', 'Getting Started', 'Using GPU code']
- ['about.md', 'Getting Started', 'About']

- ['functions.md', 'Functions', 'Overview']
- ['mfiles/vl_argparse.md', 'Functions', 'vl_argparse']
- ['mfiles/vl_compilenn.md', 'Functions', 'vl_compilenn']
- ['mfiles/vl_nnbnorm.md', 'Functions', 'vl_nnbnorm']
- ['mfiles/vl_nnspnorm.md', 'Functions', 'vl_nnspnorm']
- ['mfiles/vl_nnpdist.md', 'Functions', 'vl_nnpdist']
- ['mfiles/vl_nnconv.md', 'Functions', 'vl_nnconv']
- ['mfiles/vl_nnconvt.md', 'Functions', 'vl_nnconv']
- ['mfiles/vl_nndropout.md', 'Functions', 'vl_nndropout']
- ['mfiles/vl_nnloss.md', 'Functions', 'vl_nnloss']
- ['mfiles/vl_nnnoffset.md', 'Functions', 'vl_nnnoffset']
- ['mfiles/vl_nnnormalize.md', 'Functions', 'vl_nnnormalize']
- ['mfiles/vl_nnpool.md', 'Functions', 'vl_nnpool']
- ['mfiles/vl_nnrelu.md', 'Functions', 'vl_nnrelu']
- ['mfiles/vl_nnsigmoid.md', 'Functions', 'vl_nnsigmoid']
- ['mfiles/vl_nnsoftmax.md', 'Functions', 'vl_nnsoftmax']
- ['mfiles/vl_nnsoftmaxloss.md', 'Functions', 'vl_nnsoftmaxloss']
- ['mfiles/vl_rootnn.md', 'Functions', 'vl_rootnn']
- ['mfiles/vl_setupnn.md', 'Functions', 'vl_setupnn']
- ['mfiles/vl_simplenn.md', 'Functions', 'vl_simplenn']
- ['mfiles/vl_simplenn_diagnose.md', 'Functions', 'vl_simplenn_diagnose']
- ['mfiles/vl_simplenn_display.md', 'Functions', 'vl_simplenn_display']
- ['mfiles/vl_simplenn_move.md', 'Functions', 'vl_simplenn_move']

- ['developers.md', 'Developers', 'Developer notes']
- ['install-alt.md', 'Developers', 'Compiling from the command line']